# Generated by Django 4.1.6 on 2023-02-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvprapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=200)),
                ('timage', models.ImageField(upload_to='pic')),
                ('tdesc', models.TextField()),
            ],
        ),
    ]
